### ISSUE TITLE
Django 5.1: ImportError: cannot import name 'get_storage_class' from 'django.core.files.storage' 

### ISSUE THREAD

**Issue by PetrDlouhy** [torchbox/wagtail-storages#49]
When I tried to use `django-storages` with Django 5.1 I have got following error:

```
Traceback (most recent call last):
  File "/home/petr/soubory/programovani/blenderkit/blenderhub_server/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/wagtail_storages/apps.py", line 10, in ready
    from wagtail_storages import signal_handlers
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/wagtail_storages/signal_handlers.py", line 9, in <module>
    from wagtail_storages.utils import (
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/wagtail_storages/utils.py", line 4, in <module>
    from django.core.files.storage import get_storage_class
ImportError: cannot import name 'get_storage_class' from 'django.core.files.storage' (/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/core/files/storage/__init__.py
```

**Comment by jrthorne** [comment]
The error message by the OP is not for django-storages but wagtail_storages. I am having the same error. This is marked as fixed, but I just installed the below and am getting the below error. I must admit that the messaging here is rather terse. the fix linked above rererences commit
451fcbe
which does  not exist on the repo for wagtail storages repository linked in the github issue above:
https://github.com/torchbox/wagtail-storages/pull/50
which says the solution is:
https://github.com/torchbox/wagtail-storages/commit/451fcbe45710601d0faafd75034c0153daa734c2
which is an update to a KVPair in a YML file. 
==== BELOW requirements.txt
requests
Django==5.1
django-grappelli==3.0.3
django-session-security
wagtail==6.3
Pillow==9.2.0
# REALLY IMPORTANT, mysql does not support python3. This is the workaround
mysqlclient==2.1.1
sentry-sdk==1.13.0
#-e git://github.com/darklow/django-suit.git@v2#egg=django-suit
# This is now local - django-suit https://github.com/darklow/django-suit/tarball/v2
django-extensions==3.2.1
django-environ==0.9.0
django-dirtyfields==1.8.2
django-global-permissions==0.2.6
django-mathfilters==1.0.0
django-crispy-forms==1.14.0
django-select2==7.10.1
django-compressor==4.5.1
django-htmlmin==0.11.0
# https://github.com/Pithikos/django-compressor-postcss
# can't use this - django-compressor-postcss==0.8.2
django-sass-processor==1.2.1
libsass==0.21.0
#beautifulsoup4<4.6.1,>=4.5.1
beautifulsoup4==4.11.1
django-bootstrap-datepicker-plus
ua-parser==0.16.1
django-user-agents==0.4.0
user-agents==2.2.0
djangorestframework
